msgid ""
msgstr ""
"Project-Id-Version: pylav\n"
"POT-Creation-Date: 2023-02-02 22:15+0000\n"
"PO-Revision-Date: 2023-02-02 22:33\n"
"Last-Translator: \n"
"Language-Team: Dutch\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.4.2\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: pylav\n"
"X-Crowdin-Project-ID: 535244\n"
"X-Crowdin-Language: nl\n"
"X-Crowdin-File: /lib/pylav/extension/bundled_node/locales/messages.pot\n"
"X-Crowdin-File-ID: 3385\n"
"Language: nl_NL\n"

#: pylav/extension/bundled_node/manager.py:227
msgid "You are attempting to run the managed Lavalink node on an unsupported machine architecture."
msgstr "U probeert het beheerde Lavalink-knooppunt uit te voeren op een niet-ondersteunde machinearchitectuur."

#: pylav/extension/bundled_node/manager.py:452
msgid "The output of `{command_name}` was unexpected\n"
"{command_output}"
msgstr "De output van '{command_name}' was onverwacht\n"
"{command_output}"

#: pylav/extension/bundled_node/manager.py:472
msgid "Port {port_value} already in use. Managed Lavalink startup has been aborted."
msgstr "Haven {port_value} al in gebruik. Managed Lavalink startup is afgebroken."

#: pylav/extension/bundled_node/manager.py:477
msgid "Lavalink failed to start: {error_value}"
msgstr "Lavalink kan niet starten: {error_value}"

